name: Manual Version Bump

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version number (e.g., 1.1)'
        required: true
        default: '1.1'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump version
        run: |
          echo "${{ github.event.inputs.new_version }}" > VERSION
          git add VERSION
          git commit -m "🔖 Bump version to ${{ github.event.inputs.new_version }}"
          git tag "v${{ github.event.inputs.new_version }}"
          git push origin main --tags
          git push
